# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 4
  ParameterListWrapping:
    indentSize: 4
  NoSemicolons:
    active: false
  ChainWrapping:
    active: false
  NoTrailingSpaces:
    active: false

complexity:
  NestedBlockDepth:
    active: false
  TooManyFunctions:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

style:
  ReturnCount:
    active: false